# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form_memo(object):
    def setupUi(self, Form_memo):
        Form_memo.setObjectName("Form_memo")
        Form_memo.resize(900, 600)
        Form_memo.setMinimumSize(QtCore.QSize(900, 600))
        Form_memo.setStyleSheet(
            "\n"
            "    QWidget {\n"
            "      background-color: #f5f5f5;\n"
            '      font-family: "Microsoft YaHei";\n'
            "    }\n"
            "    QPushButton {\n"
            "      background-color: #4a90e2;\n"
            "      color: white;\n"
            "      border: none;\n"
            "      padding: 8px 16px;\n"
            "      border-radius: 4px;\n"
            "    }\n"
            "    QPushButton:hover {\n"
            "      background-color: #357abd;\n"
            "    }\n"
            "    QLineEdit, QPlainTextEdit, QListView {\n"
            "      background-color: white;\n"
            "      border: 1px solid #dcdcdc;\n"
            "      border-radius: 4px;\n"
            "      padding: 4px;\n"
            "    }\n"
            "    QLabel {\n"
            "      color: #333333;\n"
            "      font-size: 14px;\n"
            "    }\n"
            "   "
        )
        self.verticalLayout = QtWidgets.QVBoxLayout(Form_memo)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox_input = QtWidgets.QGroupBox(Form_memo)
        self.groupBox_input.setObjectName("groupBox_input")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_input)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.plainTextEdit_text_input = QtWidgets.QPlainTextEdit(self.groupBox_input)
        self.plainTextEdit_text_input.setObjectName("plainTextEdit_text_input")
        self.verticalLayout_2.addWidget(self.plainTextEdit_text_input)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_audio_input = QtWidgets.QPushButton(self.groupBox_input)
        icon = QtGui.QIcon()
        icon.addPixmap(
            QtGui.QPixmap("../assets/mic.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off
        )
        self.pushButton_audio_input.setIcon(icon)
        self.pushButton_audio_input.setObjectName("pushButton_audio_input")
        self.horizontalLayout_2.addWidget(self.pushButton_audio_input)
        self.pushButton_extract = QtWidgets.QPushButton(self.groupBox_input)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(
            QtGui.QPixmap("../assets/extract.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off
        )
        self.pushButton_extract.setIcon(icon1)
        self.pushButton_extract.setObjectName("pushButton_extract")
        self.horizontalLayout_2.addWidget(self.pushButton_extract)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout.addWidget(self.groupBox_input)
        self.groupBox_output = QtWidgets.QGroupBox(Form_memo)
        self.groupBox_output.setObjectName("groupBox_output")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_output)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.comboBox_filter = QtWidgets.QComboBox(self.groupBox_output)
        self.comboBox_filter.setObjectName("comboBox_filter")
        self.comboBox_filter.addItem("")
        self.comboBox_filter.addItem("")
        self.comboBox_filter.addItem("")
        self.verticalLayout_3.addWidget(self.comboBox_filter)
        self.listView_list_output = QtWidgets.QListView(self.groupBox_output)
        self.listView_list_output.setAlternatingRowColors(True)
        self.listView_list_output.setObjectName("listView_list_output")
        self.verticalLayout_3.addWidget(self.listView_list_output)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")

        # 添加导入按钮
        self.pushButton_import = QtWidgets.QToolButton(self.groupBox_output)
        icon_import = QtGui.QIcon()
        icon_import.addPixmap(
            QtGui.QPixmap("../assets/import.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off
        )
        self.pushButton_import.setIcon(icon_import)
        self.pushButton_import.setPopupMode(QtWidgets.QToolButton.MenuButtonPopup)
        self.pushButton_import.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.pushButton_import.setObjectName("pushButton_import")

        # 创建导入菜单
        self.import_menu = QtWidgets.QMenu(self.groupBox_output)
        self.import_excel_action = QtWidgets.QAction("从Excel导入", self.import_menu)
        self.import_txt_action = QtWidgets.QAction("从TXT导入", self.import_menu)
        self.import_menu.addAction(self.import_excel_action)
        self.import_menu.addAction(self.import_txt_action)
        self.pushButton_import.setMenu(self.import_menu)

        # 添加导出按钮
        self.pushButton_export = QtWidgets.QToolButton(self.groupBox_output)
        icon_export = QtGui.QIcon()
        icon_export.addPixmap(
            QtGui.QPixmap("../assets/export.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off
        )
        self.pushButton_export.setIcon(icon_export)
        self.pushButton_export.setPopupMode(QtWidgets.QToolButton.MenuButtonPopup)
        self.pushButton_export.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.pushButton_export.setObjectName("pushButton_export")

        # 创建导出菜单
        self.export_menu = QtWidgets.QMenu(self.groupBox_output)
        self.export_excel_action = QtWidgets.QAction("导出为Excel", self.export_menu)
        self.export_txt_action = QtWidgets.QAction("导出为TXT", self.export_menu)
        self.export_menu.addAction(self.export_excel_action)
        self.export_menu.addAction(self.export_txt_action)
        self.pushButton_export.setMenu(self.export_menu)

        # 添加清除按钮
        self.pushButton_clearall = QtWidgets.QPushButton(self.groupBox_output)
        icon_clear = QtGui.QIcon()
        icon_clear.addPixmap(
            QtGui.QPixmap("../assets/clear.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off
        )
        self.pushButton_clearall.setIcon(icon_clear)
        self.pushButton_clearall.setObjectName("pushButton_clearall")

        # 添加到布局
        self.horizontalLayout_3.addWidget(self.pushButton_import)
        self.horizontalLayout_3.addWidget(self.pushButton_export)
        self.horizontalLayout_3.addWidget(self.pushButton_clearall)

        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.horizontalLayout.addWidget(self.groupBox_output)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Form_memo)
        QtCore.QMetaObject.connectSlotsByName(Form_memo)

    def retranslateUi(self, Form_memo):
        _translate = QtCore.QCoreApplication.translate
        Form_memo.setWindowTitle(_translate("Form_memo", "智能备忘录"))
        self.groupBox_input.setTitle(_translate("Form_memo", "输入区域"))
        self.plainTextEdit_text_input.setPlaceholderText(
            _translate("Form_memo", "请输入您的备忘内容...")
        )
        self.pushButton_audio_input.setText(_translate("Form_memo", "语音输入"))
        self.pushButton_extract.setText(_translate("Form_memo", "提取事项"))
        self.groupBox_output.setTitle(_translate("Form_memo", "任务列表"))
        self.comboBox_filter.setItemText(0, _translate("Form_memo", "全部任务"))
        self.comboBox_filter.setItemText(1, _translate("Form_memo", "今日任务"))
        self.comboBox_filter.setItemText(2, _translate("Form_memo", "周期任务"))
        self.pushButton_import.setText(_translate("Form_memo", "导入"))
        self.pushButton_export.setText(_translate("Form_memo", "导出"))
        self.pushButton_clearall.setText(_translate("Form_memo", "清除"))
